name       : cava
version    : 0.4.3
release    : 4
source     :
    - https://github.com/karlstav/cava/archive/0.4.3.tar.gz : 9aa6a7c97b8877a6ba3bfa037cb74ee8c77b71fa1020a1507425890d676e20fb
license    : MIT
component  : multimedia.audio
summary    : Console-based Audio Visualizer for Alsa
description: |
    Console-based Audio Visualizer for Alsa
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
setup      : |
    sed -i "s|local/lib|lib64|g" Makefile.am
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
