name       : cava
version    : 0.6.0
release    : 5
source     :
    - https://github.com/karlstav/cava/archive/0.6.0.tar.gz : 42d51c6c283cd2b0f5125954ea8c61a12385703d1953ef9c40103402c7a744dc
license    : MIT
component  : multimedia.audio
summary    : Console-based Audio Visualizer for Alsa
description: |
    Console-based Audio Visualizer for Alsa
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
setup      : |
    sed -i "s|local/lib|lib64|g" Makefile.am
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
