name       : cava
version    : 0.7.3
release    : 9
source     :
    - https://github.com/karlstav/cava/archive/0.7.3.tar.gz : 6363347ef4c74770767d9aa2fb5d65ad4c2aedf1d23bdaac50fc8e8e4e3c707e
license    : MIT
component  : multimedia.audio
summary    : Console-based Audio Visualizer for Alsa
description: |
    Console-based Audio Visualizer for Alsa
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(libpulse)
setup      : |
    sed -i "s|local/lib|lib64|g" Makefile.am
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
