name       : cava
version    : 0.8.3
release    : 11
source     :
    - https://github.com/karlstav/cava/archive/refs/tags/0.8.3.tar.gz : ce7378ababada5a20fa8250c6b3fe6412bc1a7dd31301a52b8b4a71d362875b9
homepage   : https://github.com/karlstav/cava
license    : MIT
component  : multimedia.audio
summary    : Console-based Audio Visualizer for Alsa
description: |
    Cava is a bar spectrum audio visualizer for terminal (ncurses) or desktop (SDL).
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(iniparser)
    - pkgconfig(libpulse)
setup      : |
    sed -i "s|local/lib|lib64|g" Makefile.am
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
